apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cloudflared-to-ghost
  namespace: blog
spec:
  podSelector:
    matchLabels:
      app: ghost
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cloudflare
          podSelector:
            matchLabels:
              app: cloudflared
      ports:
        - protocol: TCP
          port: 2368
