apiVersion: ENC[AES256_GCM,data:ZWs=,iv:RsElZHCetWbyOS9MXrLzWFGWlplw9zwIY9dYIS7RMkQ=,tag:GkH+FsVLH1CvY/2UTjwQ0g==,type:str]
kind: ENC[AES256_GCM,data:0Kjg+XJI,iv:ZA30HOXs8a3EbmMA8GHJx06GOQ4CwU7PtwZaLpWn+qQ=,tag:K4xgpH2ysYKIPrQ8T3WNsQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:M8Y8WLywJBMZ7g==,iv:nECoiyXCO2LFA3RtmHdfJej4Xzdvdy/86IaVQI3AE3w=,tag:YHqYe74MQJ87UyMa4nMVTA==,type:str]
    namespace: ENC[AES256_GCM,data:Pd2f3Q==,iv:y7HQOfJpZ+AXdRY8v2o6MHBW7ygHgoFtL/qcYVvXK1s=,tag:swiWhyQC1YLQVa1tP7sNSA==,type:str]
type: ENC[AES256_GCM,data:WeYR+f28,iv:Lav3OFJyDvK9NeVO7r67ymHUra1wEPGv2t3wR6kf33M=,tag:6QdHbDDa8A0KdJXxsIHsmQ==,type:str]
stringData:
    password: ENC[AES256_GCM,data:d16yAbdWNXoSq+CgpiHgR+mIDrIVzTXpOXyVYryl6hTv8+OJ5+gBEJrpffKORe6YmmD+wV0mvC6VDNC79URZvlY9HVAdzo7tLSRFU9pLp4b0R2nIPo+IylEW,iv:feuqyLH9Nk0RjO9zeg4k5qAapIbiVb6YiADdvL+Jc+k=,tag:ke/wWOkOC9IBMtJr/tzSrw==,type:str]
sops:
    age:
        - recipient: age19pulnwtzah3x4xfp8rsajr7vzddct6lljeurfgu3pc7t9v3cy4gq6xe297
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YzRWNDlJRGZVQzJFczJ5
            dzFXbEtKUWU2ZndKU0VIajVWUzV0RFl0dmdBCnlWbDdSWkFvb1ZIS3RJeWRoQ1Yw
            MnVpazBqaHZiMG4vZ3E3d0pVMy9pencKLS0tIEJIb3BwK2lMd25ycGJtbE8xTWp1
            czJNY2s1TWQwUDlFWjByT0RrWGxhTkEKK1clY0iesMSrBGbOVZBLAQ5RyJz1B697
            54HSRFqe5XaSXz7hu+wumA47j03z7ZjoUUXNicIZhWzJ3EmYqjYRkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T03:13:57Z"
    mac: ENC[AES256_GCM,data:w7qCALZ5Xr6p1wjEH5a1qNQy+Bf4A3fjX47BSG6plW/z+nAjGo+S9FyQl7qJQ+J505yrBgLu/iopFel/Ea+ZrdYNvdVoVmoVhHp7Kt5c2FH2uVjoGGtcBfkvqwpFM1dEBfqRiIrYYV9/o78BMXn6hDnjKmJ/F2zLEFWK+eGjrSo=,iv:HtwMvk/ykLe1mBCvpxABCVXp/hon526IZdwDks+TkkE=,tag:ZGU80hCu8nInMOC35rbP+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
