all:
  children:
    k3s_servers:
      hosts:
        homie-k8s-node-1:
          ansible_host: 192.168.6.200
    k3s_agents:
      hosts:
        homie-k8s-node-2:
          ansible_host: 192.168.6.201
  vars:
    ansible_user: charlie
    ansible_python_interpreter: /usr/bin/python3
