apiVersion: ENC[AES256_GCM,data:MzE=,iv:rGYWmAGnYmOi0wI6pxxh0sUJc+MFUnsNhbfAp+4ANFo=,tag:a4OYxe1olDwcEJkJgy5ptw==,type:str]
kind: ENC[AES256_GCM,data:h3hUOBQE,iv:Pu0/mdfpdEt4IaSN2F87gR6q+orv+zHRKtbJFkcrRmE=,tag:GUsZvVnMnSuFbpkeJvklHw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:up6kG/0UeeyV7TTV65fhFp8AaiO54TnD,iv:zLj3m18eV6bIgV0xWbjtkLyATZBgcXoLguy81uLnkCA=,tag:mnAxa2tmdSPPIpdxF+qprg==,type:str]
    namespace: ENC[AES256_GCM,data:rc+Pzv0xb9u/YQ==,iv:Q23ElfKt/anMt4H9bgdfT2NSvGHN7LiFHwBISqBV/p8=,tag:u5/T2HmscMI/T5Y4lexArg==,type:str]
type: ENC[AES256_GCM,data:ickMuRsq,iv:MBEvM89l+fNIKFyvf2afUbsR+6TzITFrpEZY0ghq+9U=,tag:LvFfO1sLCuMNrggeb28UVQ==,type:str]
stringData:
    token: ENC[AES256_GCM,data:Pb6+J4xSjBK97xEBVY4Uk2QFu7j/BmDDPmHeZvLHmC3uuPiMexojedRJ/mJy8BPTxU7l6ZlVntiXVVOUREfXaR9Ig7ZmBESei11OcYxpn76N6Sff3fZY92qKwPqnm5j6X7EcrnvPnjvUklNXoZ8bB5luFXePr2frHRaQ7U9T7b93Zz25n5vsy3C+xo1XWMnzQ58dY/cZpRV2+OAdKRsLCWxIbTE7qCqlFe3ExBH3nxCLL06v7NfiOw==,iv:sMZqG4aXNEdck7ZHMTljbjLCOiOYeC5zSovGXWZV/j0=,tag:Wwd7n32hClnLsujBilrEvw==,type:str]
sops:
    age:
        - recipient: age19pulnwtzah3x4xfp8rsajr7vzddct6lljeurfgu3pc7t9v3cy4gq6xe297
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEektNRHErVWpXRkZON292
            c0U4NXJ5QlZkam9lL2FhMlpwWFIxS1FhUFU0CmhuS1llWW55ZWFMZjg4NFZpS1lq
            RGNYMHhvUDBZYkZkRytiR1pCZnF0UTQKLS0tIHVnc3czMEJscUNXVzI5eGk5Z2dw
            YmtsY3hZSjg5dTMrcDQ4U1NpZElxVmcKMdkOB0Rn0vnwvi0r8YnuAqIY/uAr7iT6
            OP3aH/1B/fhDzAuzJXG3XDHBIKb+NeBGta88lqVSutME9573yEvQWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T18:48:39Z"
    mac: ENC[AES256_GCM,data:1IJsgkxC6GRdgCNPGu/x3/Xdt7BPZ5Z/xXCPEJB+7LwB0hT6RgePk3oq9KtL5SW6StEeH7fqiAuGtuBJYTzjq8aVeUxVRBhsIMB4j3CVxFaVe2rnTVttiL714c9VyO6xpGE0AfIUqHW+E6E4REzze0/UQO5QiFapAYM928JmBv4=,iv:gjo/6bCcbQPKTvOBNJ3pZF0MvJ+nRMaeqtoJQCAD59c=,tag:bpA/mTv4Dwfdm5yeDV+fsA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
